- id: pylint
  name: pylint
  entry: python -m pylint .
  language: system
  types: [python]
  pass_filenames: false

- id: pytest
  name: pytest
  entry: python -m pytest
  language: system
  types: [python]
  pass_filenames: false

- id: unittest
  name: unittest
  entry: python -m unittest
  language: system
  types: [python]
  pass_filenames: false
